In [1]:
import numpy as np

##### Parte 1: Numpy

1) ¿Cuál es el tamaño en bytes de un array de 1000
elementos de tipo booleano?

In [6]:
array_1 = np.zeros(1000, dtype=bool)

In [7]:
tamanio_en_bytes = array_1.nbytes

In [8]:
tamanio_en_bytes

1000

2) Cree un array cuyos elementos sean los enteros pares en
[1,100] y en orden decreciente. Muestre los 10 últimos
por pantalla.

In [29]:
array_2 = np.arange(2, 102, 2)
array_2 = np.sort(array_2)[::-1]


In [37]:
array_2[-10:]

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

3) Dado el array
2 4 5 6
0 3 7 4
8 8 5 2
1 5 6 1
Seleccione con una instrucción el subarray de elementos
0 3 7 4
Después, seleccione el subarray de elementos
2 5
8 5

In [44]:
array_3 = np.array([[2,4,5,6], [0,3,7,4], [8,8,5,2], [1,5,6,1]])

In [51]:
array_3

array([[2, 4, 5, 6],
       [0, 3, 7, 4],
       [8, 8, 5, 2],
       [1, 5, 6, 1]])

In [47]:
array_3[1]

array([0, 3, 7, 4])

In [58]:
np.array([[array_3[0][0], array_3[0][2]], [array_3[2][0], array_3[2][2]]])

array([[2, 5],
       [8, 5]])

4) Dados los arrays a = [1, 4, 2, 7] y b = [1, 3, 2, 9],
obtenga la media aritmética de la diferencia (a-b).

In [59]:
array_a = np.array([1,4,2,7])
array_b = np.array([1,3,2,9])

In [60]:
np.mean(array_a-array_b)

-0.25

5) Tengo valores de cordenadas (x, y) en las columnas
del array
1.33 4.5
30.0 10.7
70.2 0.5

Agregue a este array las coordenadas (37.1, -3.6).
Muestre en pantalla las dimensiones del nuevo
array.

In [78]:
array_5 = np.array([[1.33,4.5], [30.0, 10.7], [70.2, 0.5]])

In [79]:
array_5

array([[ 1.33,  4.5 ],
       [30.  , 10.7 ],
       [70.2 ,  0.5 ]])

In [81]:
array_5 = np.append(array_5, [37.1, -3.6])

In [82]:
array_5

array([ 1.33,  4.5 , 30.  , 10.7 , 70.2 ,  0.5 , 37.1 , -3.6 ])

6) Copie el array del ejercicio anterior. Traspóngalo (.
Agregue ahora dos nuevos pares de coordenadas: (10.8,
3.0) y (35.8, 12.0).